### ISSUE TITLE
host.docker.internal not supported

### ISSUE THREAD

**Issue by rburgst** [Parallels/docker-machine-parallels#101]
newer docker for mac versions support mapping the docker host address to `host.docker.internal`, see also https://docs.docker.com/docker-for-windows/networking/

this is not supported in docker machine for parallels.

**Comment by legal90** [comment]
Hi @rburgst 
Yes, I can confirm it's not supported in Docker Machine, but there is nothing what we can do with that on our plugin side. 
And unfortunately I don't think it will ever be available in Docker Machine, because both Docker Machine and boot2docker (the Linux distribution with Docker Engine) are in maintenance mode / end-of-support:
- https://github.com/docker/machine/issues/4537
- https://github.com/boot2docker/boot2docker/pull/1408

I can only recommend you trying the explicit `--add-host` argument (or its analogue for docker-compose if you use it):
```
$ docker run -it --add-host=host.docker.internal:$(docker-machine ip) alpine cat /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
10.211.55.80	host.docker.internal
172.17.0.2	063361bb830b
```

**Comment by rburgst** [comment]
Thanks a lot for your prompt reply!
