### ISSUE TITLE
Q: Is there a way to use shared folders when used with minikube?

### ISSUE THREAD

**Issue by fpatz** [Parallels/docker-machine-parallels#109]
After some digging, I've found that this projects serves as the Parallels driver for minikube. I've tried to setup shared host folders for the Parallels VM provisioned by this driver, but I could not find a way to do it. Since the VM generated for docker-machine is basically the same, I'd assume it should be doable in principle -- does minikube just lack a way of passing the necessary information?

**Comment by legal90** [comment]
Hi @fpatz,
It's not possible to use "naive" Parallels Shared Folders in the minikube VM because the boot image used by minikube (for insance, `minikube-v1.25.0.iso`) doesn't have Parallels Tools installed. So that, the `prl_fs` filesystem is not availble in the VM.

However, you can still make custom shared folders working by using the default mechanism of minikube - 9P protocol. 
More info and examples:
- https://minikube.sigs.k8s.io/docs/handbook/mount/#9p-mounts
- https://stackoverflow.com/questions/48534980/mount-local-directory-into-pod-in-minikube

Since 9P works via the network interface, it's working fine with parallels driver too:
```
$ minikube start --driver parallels --mount-string="/Users/me/data:/data" --mount 
<...>
$ minikube ssh -- ls -la /data
<the content of my folder on the mac host>
```

**Comment by fpatz** [comment]
Thanks for the reply! I was asking since the 9P mounts are much slower than ``prl_fs``. Will try my luck with a regular Linux VM on Parallels then ...

**Comment by legal90** [comment]
@fpatz Sure! I can recommend trying Vagrant with our provider [`vagrant-parallels`](https://github.com/Parallels/vagrant-parallels) for creating a regular VM fast and easy.

There are base boxes for Vagrant with `parallels` provider support, which already have Parallels Tools installed: 
https://app.vagrantup.com/boxes/search?utf8=%E2%9C%93&sort=downloads&provider=parallels&q=bento
