### ISSUE TITLE
Shared volume disappears after shut down

### ISSUE THREAD

**Issue by ianbytchek** [Parallels/docker-machine-parallels#14]
For some reason, every time I shut down (by quitting parallels) the vm, the `/Users` volume disappears resulting in a whole bunch of issues when starting docker with mounted volumes. Is there a way to manually mount the volume before there's a better solution?

**Comment by legal90** [comment]
@ianbytchek Do you mean that you stop the VM and then you start it again via Parallels Desktop GUI, so after that Shared folders are not mounted?

**Comment by ianbytchek** [comment]
@legal90 yep. I normally don't intentionally stop it, just quit parallels or restart the computer all together. It did happen a few times before, but I though that it's related to something else. Recreated the vm several times, and now it happened right after I quit parallels to free up memory and then started it again.

**Comment by legal90** [comment]
@ianbytchek You can shut down the VM via Parallels Desktop GUI (or by quitting it), but if you want to start it again, you should do it with docker-machine command:

```
docker-machine start <you_vm_name>
```

This command not only starts the VM , but it also cares about VM IP address and shared folder mounting.

**Comment by ianbytchek** [comment]
@legal90 phew, worked. Thanks! Was wondering lately. When I create new vm with parallels driver it always assigns a new ip, though all previous vms are removed. This is inconvenient since I have to reconfigure several dependencies to use the new ip. With virtual box we always used to get ip that didn't change. Is that possible? Didn't find any docker machine options for that.

**Comment by legal90** [comment]
Some details:
Parallels Desktop has internal mechanism for shared folder auto-mounting, but it mounts them to pre-defined path `/media/psf/<share_name>`. 

For Docker purposes we don't need this path, because we want host's `/Users` to be mounted exactly to the guest's `/User`. That's why in our docker-machine driver we've disable Parallels built-in auto-mount feature, so we mount shares on the `Start` step in docker-machine:
https://github.com/Parallels/docker-machine-parallels/blob/master/parallels.go#L456-L461

**Comment by ianbytchek** [comment]
@legal90 thanks, that's good to know. Closing this. 

P.S. Would appreciate any feedback on ip subject.

**Comment by legal90** [comment]
> When I create new vm with parallels driver it always assigns a new ip, though all previous vms are removed.

Each new VM has an original MAC address, so internal DHCP server generates a unique IP for it. But normally this IP is not changing during the VM lifecycle (because MAC is unchanged).
In VirtualBox there is absolutely another situation, because its NAT address space is not shared between VMs.

> Is that possible?

There is only a dirty hack. If you re-create the VM by some reason, the only way to keep an old IP address is to use the same MAC address. 
Before deleting the old VM you should copy it's MAC address (for "Shared" adapter), then delete the VM. After that apply saved MAC to the new VM and then start/reboot it.

However, in Parallels Desktop 11 we have a useful feature - you can use a VM name as its hostname. So, there is no need to worry about VM IP addresses.
When the VM is running, you can access it by its name:
```
$ docker-machine start b2d-prl
...

$ ping b2d-prl
PING b2d-prl.shared (10.211.55.167): 56 data bytes
64 bytes from 10.211.55.167: icmp_seq=0 ttl=64 time=0.441 ms
64 bytes from 10.211.55.167: icmp_seq=1 ttl=64 time=0.489 ms
64 bytes from 10.211.55.167: icmp_seq=2 ttl=64 time=0.296 ms
```
This hostname is resolvable from your host and from other VMs as well.
It is implemented through auto-managed entries in `/etc/hosts` on your Mac:

```bash
$ cat /etc/hosts
# whatever
# ...
10.211.55.167  	b2d-prl.shared b2d-prl #prl_hostonly shared
```

**Comment by ianbytchek** [comment]
It kind of worked. I needed this for a haproxy container to send traffic to a sibling container, which would require real-time reconfiguration or something like exposing ports and pointing to a higher level ip. But the machine name works just as good. But there's also a dnsmasq running on mac, and it seems it doesn't like all that. The docs say that domain name would be fine, but when I change config from `address=/amazonaws.dev/10.211.55.48` to `address=/amazonaws.dev/default/` Chrome returns `DNS_PROBE_FINISHED_NXDOMAIN` error. Nevertheless, all very helpful, thanks @legal90!
