### ISSUE TITLE
volumes doesn't work

### ISSUE THREAD

**Issue by appelgriebsch** [Parallels/docker-machine-parallels#20]
I created a docker machine using the parallels driver here and though it allows me to connect to the docker host on the VM from my Mac machine, it doesn't mount the directories I specify on the docker run command as volumes from the Mac to the VM correctly (they are just empty within my running container)...

e.g.
```bash
docker run -it --rm -v ~/MyVol:/data mycontainer bash
```
ls -al /data
would return an empty folder...

**Comment by legal90** [comment]
Please, check that shared folder is mounted in the virtual machine and files are available:
$ docker-machine ssh <your_vm_name> -- ls $HOME/Documents/test-docker-machine

- If you see the list of your files, then the problem is not related to docker-machine (but to docker itself, may be).

- If you see `No such file or directory` error, then shared folder is not mounted. In this case, please ensure that you've started your VM via `docker-machine` command, not from Parallels Desktop GUI (refer to https://github.com/Parallels/docker-machine-parallels/issues/14 for more info)
You can just run `docker-machine restart <your_vm_name>` and try your `docker run` command again.

**Comment by appelgriebsch** [comment]
Thanks for immediate reply. docker-machine start does the trick.

**Comment by legal90** [comment]
Ok, good. I'm sorry for that inconvenience. 

Seems like we have to add some `prl_fs` auto-mount script to the Boot2Docker distribution.
