### ISSUE TITLE
Support "bridged" network mode

### ISSUE THREAD

**Issue by sheerun** [Parallels/docker-machine-parallels#41]
Hey

This driver for now uses `/Library/Preferences/Parallels/parallels_dhcp_leases` that shows ip assigned by parallels' dhcp. I changed network mode of contained to "bridge" so my containers are exposed in local network, but `docker-machine ip` still shows old ip address from `parallels_dhcp_leases`.

Could you implement support for bridged mode, please?

**Comment by legal90** [comment]
Hi @sheerun 
Thank you for request! Like in Vagrant provider, here in Machine driver we use "Shared" network configuration by default, because it works for everybody and it doesn't depend on any external conditions.
However, "bridged" mode depends on the configuration of a network, which the host machine is currently connected to. There could be a static IP in some specific subnet or an auto-configuration by DHCP. 

Adding "bridged" mode as an additional option sounds good, and we're open for Pull-Requests allowing this. But honestly, I'm not sure how it could lay on the Docker Machine workflow.
Also I'm looking forward to the way how the similar feature will be implemented in the upstream Docker Machine for the VirtualBox driver: https://github.com/docker/machine/issues/1491

At the moment, I recommend you to add a second network adapter with a type "Bridge", because reconfiguring of the existing one will brake the Docker Machine driver - it won't be able to connect to the VM.

**Comment by dersimn** [comment]
+1

**Comment by Elhodred** [comment]
Adding a second adapter works only if you access your containers from the same network configured in the bridge interface.
This is due the fact that you will end up with 2 default routes in the routing table:
docker@default:~$ ip route list
default via 10.211.55.1 dev eth0  metric 1 
default via 192.168.1.1 dev eth1  metric 1 

I don't find a way to remove persistently the "wrong" default route that makes my setup working.
Is there a way to reconfigure the VM to have only one interface in a way that the connection from docker-machine is not broken?

**Comment by HunterDG** [comment]
Glad I found this issue!

Workaround:
`docker-machine create --driver parallels default`
`docker machine env` to find the "Shared" IP
`docker-machine stop`
change the network interface to bridged in parallels config, then manually start the VM
run `ip a` in the docker VM to find new bridged IP
replace "Shared" with bridged IP in `/Library/Preferences/Parallels/parallels_dhcp_leases`, save file
`docker-machine regenerate-certs default`
`docker-machine env`

Voila! :) (until DHCP lease changes on bridged network, or parallels decides to overwrite the dhcp leases file)

Alternative more permanent workaround I haven't tried (and assuming no other VMs use shared networking) could be to set a DHCP reservation in the bridged network DHCP server, then modify Parallels "Shared" network DHCP prefs to hand out only that IP address.  Then you'd theoretically only need to change the network interface to bridged, and presumably Parallels wouldn't overwrite the DHCP leases file.

**Comment by caffeineflo** [comment]
Nice workaround. 

It seems though as restarting the docker machine will invalidate the certificates/docker remote API and you'd have to reprovision/regenerate the certs again. Very unfortunate

**Comment by legal90** [comment]
Hi all,
Since Docker Machine was put into the maintenance mode (https://github.com/docker/machine/issues/4537) there is almost no chance that the Bridge network support will be officially added there (https://github.com/docker/machine/issues/1491).
Therefore, we are not going to implement it in parallels driver neither. 

Those of you, who still need that, I would recommend using the workaround posted by @HunterDG in the comment above.

**Comment by HunterDG** [comment]
FYI - not explicitly related to this issue, but relevant to my need at the time (homebridge/other containers that require net=host only [don't work in Docker Desktop](https://docs.docker.com/network/host/))...

There is now a [homebridge-vm-image](https://github.com/homebridge/homebridge-vm-image) that negates the need for docker-machine.
