### ISSUE TITLE
Port mapping is invalid

### ISSUE THREAD

**Issue by sbfkcel** [Parallels/docker-machine-parallels#89]
![image](https://user-images.githubusercontent.com/5469785/80994825-df793c80-8e6f-11ea-9576-b89ca9357bfa.png)

Viewing the container shows that the port mapping is normal.
However, the local port is not visible.

---
The default network configuration used

**Comment by dskr99** [comment]
Please post a problem report from Parallels: Help -> Send technical data and post here it's number

**Comment by legal90** [comment]
@sbfkcel What you see in `docker ps` output is relevant to your DOCKER_HOST, which is your virtual machine created with `docker-machine`.  The port is listened on the VM interface, not on your Mac.

If you want to access the port from your Mac, get the VM's IP by running `docker-machine IP <vm name>` and use it instead of `127.0.0.1`. (ref: https://github.com/Parallels/docker-machine-parallels/issues/53#issuecomment-222762658)

In your case it will be something like this: `10.211.55.5:1081`

And this is how you can run netstat (and any other command) in your docker-machine VM:
```
docker-machine ssh <vm_name> -- netstat -nat 
```

**Comment by sbfkcel** [comment]
@legal90 Thank you. The problem is solved.
